/*
 * Copyright (C) 2023 Cobblemon Contributors
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

package com.cobblemon.mod.common.api.abilities

import com.cobblemon.mod.common.Cobblemon
import com.cobblemon.mod.common.api.registry.CobblemonRegistry
import com.cobblemon.mod.common.battles.runner.ShowdownService
import com.cobblemon.mod.common.pokemon.abilities.HiddenAbilityType
import com.cobblemon.mod.common.registry.CobblemonRegistries
import com.cobblemon.mod.common.util.asIdentifierDefaultingNamespace
import com.cobblemon.mod.common.util.cobblemonResource
import net.minecraft.core.Registry
import net.minecraft.network.chat.Component
import net.minecraft.resources.ResourceKey
import org.jetbrains.annotations.ApiStatus

/**
 * Registry for all known Abilities
 */
@Suppress("unused")
object Abilities : CobblemonRegistry<AbilityTemplate>() {

    internal val DUMMY = this.create("dummy", -1F, false, emptySet())

    @JvmStatic val NO_ABILITY = this.key("noability")
    @JvmStatic val ADAPTABILITY = this.key("adaptability")
    @JvmStatic val AERILATE = this.key("aerilate")
    @JvmStatic val AFTERMATH = this.key("aftermath")
    @JvmStatic val AIR_LOCK = this.key("airlock")
    @JvmStatic val ANALYTIC = this.key("analytic")
    @JvmStatic val ANGER_POINT = this.key("angerpoint")
    @JvmStatic val ANGER_SHELL = this.key("angershell")
    @JvmStatic val ANTICIPATION = this.key("anticipation")
    @JvmStatic val ARENA_TRAP = this.key("arenatrap")
    @JvmStatic val ARMOR_TAIL = this.key("armortail")
    @JvmStatic val AROMA_VEIL = this.key("aromaveil")
    @JvmStatic val AS_ONE_GLASTRIER = this.key("asoneglastrier")
    @JvmStatic val AS_ONE_SPECTRIER = this.key("asonespectrier")
    @JvmStatic val AURA_BREAK = this.key("aurabreak")
    @JvmStatic val BAD_DREAMS = this.key("baddreams")
    @JvmStatic val BALL_FETCH = this.key("ballfetch")
    @JvmStatic val BATTERY = this.key("battery")
    @JvmStatic val BATTLE_ARMOR = this.key("battlearmor")
    @JvmStatic val BATTLE_BOND = this.key("battlebond")
    @JvmStatic val BEADS_OF_RUIN = this.key("beadsofruin")
    @JvmStatic val BEAST_BOOST = this.key("beastboost")
    @JvmStatic val BERSERK = this.key("berserk")
    @JvmStatic val BIG_PECKS = this.key("bigpecks")
    @JvmStatic val BLAZE = this.key("blaze")
    @JvmStatic val BULLETPROOF = this.key("bulletproof")
    @JvmStatic val CHEEK_POUCH = this.key("cheekpouch")
    @JvmStatic val CHILLING_NEIGH = this.key("chillingneigh")
    @JvmStatic val CHLOROPHYLL = this.key("chlorophyll")
    @JvmStatic val CLEAR_BODY = this.key("clearbody")
    @JvmStatic val CLOUD_NINE = this.key("cloudnine")
    @JvmStatic val COLOR_CHANGE = this.key("colorchange")
    @JvmStatic val COMATOSE = this.key("comatose")
    @JvmStatic val COMMANDER = this.key("commander")
    @JvmStatic val COMPETITIVE = this.key("competitive")
    @JvmStatic val COMPOUND_EYES = this.key("compoundeyes")
    @JvmStatic val CONTRARY = this.key("contrary")
    @JvmStatic val CORROSION = this.key("corrosion")
    @JvmStatic val COSTAR = this.key("costar")
    @JvmStatic val COTTON_DOWN = this.key("cottondown")
    @JvmStatic val CUD_CHEW = this.key("cudchew")
    @JvmStatic val CURIOUS_MEDICINE = this.key("curiousmedicine")
    @JvmStatic val CURSED_BODY = this.key("cursedbody")
    @JvmStatic val CUTE_CHARM = this.key("cutecharm")
    @JvmStatic val DAMP = this.key("damp")
    @JvmStatic val DANCER = this.key("dancer")
    @JvmStatic val DARK_AURA = this.key("darkaura")
    @JvmStatic val DAUNTLESS_SHIELD = this.key("dauntlessshield")
    @JvmStatic val DAZZLING = this.key("dazzling")
    @JvmStatic val DEFEATIST = this.key("defeatist")
    @JvmStatic val DEFIANT = this.key("defiant")
    @JvmStatic val DELTA_STREAM = this.key("deltastream")
    @JvmStatic val DESOLATE_LAND = this.key("desolateland")
    @JvmStatic val DISGUISE = this.key("disguise")
    @JvmStatic val DOWNLOAD = this.key("download")
    @JvmStatic val DRAGONS_MAW = this.key("dragonsmaw")
    @JvmStatic val DRIZZLE = this.key("drizzle")
    @JvmStatic val DROUGHT = this.key("drought")
    @JvmStatic val DRY_SKIN = this.key("dryskin")
    @JvmStatic val EARLY_BIRD = this.key("earlybird")
    @JvmStatic val EARTH_EATER = this.key("eartheater")
    @JvmStatic val EFFECT_SPORE = this.key("effectspore")
    @JvmStatic val ELECTRIC_SURGE = this.key("electricsurge")
    @JvmStatic val ELECTROMORPHOSIS = this.key("electromorphosis")
    @JvmStatic val EMBODY_ASPECT_CORNERSTONE = this.key("embodyaspectcornerstone")
    @JvmStatic val EMBODY_ASPECT_HEARTHFLAME = this.key("embodyaspecthearthflame")
    @JvmStatic val EMBODY_ASPECT_TEAL = this.key("embodyaspectteal")
    @JvmStatic val EMBODY_ASPECT_WELLSPRING = this.key("embodyaspectwellspring")
    @JvmStatic val EMERGENCY_EXIT = this.key("emergencyexit")
    @JvmStatic val FAIRY_AURA = this.key("fairyaura")
    @JvmStatic val FILTER = this.key("filter")
    @JvmStatic val FLAME_BODY = this.key("flamebody")
    @JvmStatic val FLARE_BOOST = this.key("flareboost")
    @JvmStatic val FLASH_FIRE = this.key("flashfire")
    @JvmStatic val FLOWER_GIFT = this.key("flowergift")
    @JvmStatic val FLOWER_VEIL = this.key("flowerveil")
    @JvmStatic val FLUFFY = this.key("fluffy")
    @JvmStatic val FORECAST = this.key("forecast")
    @JvmStatic val FOREWARN = this.key("forewarn")
    @JvmStatic val FRIEND_GUARD = this.key("friendguard")
    @JvmStatic val FRISK = this.key("frisk")
    @JvmStatic val FULL_METAL_BODY = this.key("fullmetalbody")
    @JvmStatic val FUR_COAT = this.key("furcoat")
    @JvmStatic val GALE_WINGS = this.key("galewings")
    @JvmStatic val GALVANIZE = this.key("galvanize")
    @JvmStatic val GLUTTONY = this.key("gluttony")
    @JvmStatic val GOOD_AS_GOLD = this.key("goodasgold")
    @JvmStatic val GOOEY = this.key("gooey")
    @JvmStatic val GORILLA_TACTICS = this.key("gorillatactics")
    @JvmStatic val GRASS_PELT = this.key("grasspelt")
    @JvmStatic val GRASSY_SURGE = this.key("grassysurge")
    @JvmStatic val GRIM_NEIGH = this.key("grimneigh")
    @JvmStatic val GUARD_DOG = this.key("guarddog")
    @JvmStatic val GULP_MISSILE = this.key("gulpmissile")
    @JvmStatic val GUTS = this.key("guts")
    @JvmStatic val HADRON_ENGINE = this.key("hadronengine")
    @JvmStatic val HARVEST = this.key("harvest")
    @JvmStatic val HEALER = this.key("healer")
    @JvmStatic val HEATPROOF = this.key("heatproof")
    @JvmStatic val HEAVY_METAL = this.key("heavymetal")
    @JvmStatic val HONEY_GATHER = this.key("honeygather")
    @JvmStatic val HOSPITALITY = this.key("hospitality")
    @JvmStatic val HUGE_POWER = this.key("hugepower")
    @JvmStatic val HUNGER_SWITCH = this.key("hungerswitch")
    @JvmStatic val HUSTLE = this.key("hustle")
    @JvmStatic val HYDRATION = this.key("hydration")
    @JvmStatic val HYPER_CUTTER = this.key("hypercutter")
    @JvmStatic val ICE_BODY = this.key("icebody")
    @JvmStatic val ICE_FACE = this.key("iceface")
    @JvmStatic val ICE_SCALES = this.key("icescales")
    @JvmStatic val ILLUMINATE = this.key("illuminate")
    @JvmStatic val ILLUSION = this.key("illusion")
    @JvmStatic val IMMUNITY = this.key("immunity")
    @JvmStatic val IMPOSTER = this.key("imposter")
    @JvmStatic val INFILTRATOR = this.key("infiltrator")
    @JvmStatic val INNARDS_OUT = this.key("innardsout")
    @JvmStatic val INNER_FOCUS = this.key("innerfocus")
    @JvmStatic val INSOMNIA = this.key("insomnia")
    @JvmStatic val INTIMIDATE = this.key("intimidate")
    @JvmStatic val INTREPID_SWORD = this.key("intrepidsword")
    @JvmStatic val IRON_BARBS = this.key("ironbarbs")
    @JvmStatic val IRON_FIST = this.key("ironfist")
    @JvmStatic val JUSTIFIED = this.key("justified")
    @JvmStatic val KEEN_EYE = this.key("keeneye")
    @JvmStatic val KLUTZ = this.key("klutz")
    @JvmStatic val LEAF_GUARD = this.key("leafguard")
    @JvmStatic val LEVITATE = this.key("levitate")
    @JvmStatic val LIBERO = this.key("libero")
    @JvmStatic val LIGHT_METAL = this.key("lightmetal")
    @JvmStatic val LIGHTNING_ROD = this.key("lightningrod")
    @JvmStatic val LIMBER = this.key("limber")
    @JvmStatic val LINGERING_AROMA = this.key("lingeringaroma")
    @JvmStatic val LIQUID_OOZE = this.key("liquidooze")
    @JvmStatic val LIQUID_VOICE = this.key("liquidvoice")
    @JvmStatic val LONG_REACH = this.key("longreach")
    @JvmStatic val MAGIC_BOUNCE = this.key("magicbounce")
    @JvmStatic val MAGIC_GUARD = this.key("magicguard")
    @JvmStatic val MAGICIAN = this.key("magician")
    @JvmStatic val MAGMA_ARMOR = this.key("magmaarmor")
    @JvmStatic val MAGNET_PULL = this.key("magnetpull")
    @JvmStatic val MARVEL_SCALE = this.key("marvelscale")
    @JvmStatic val MEGA_LAUNCHER = this.key("megalauncher")
    @JvmStatic val MERCILESS = this.key("merciless")
    @JvmStatic val MIMICRY = this.key("mimicry")
    @JvmStatic val MINDS_EYE = this.key("mindseye")
    @JvmStatic val MINUS = this.key("minus")
    @JvmStatic val MIRROR_ARMOR = this.key("mirrorarmor")
    @JvmStatic val MISTY_SURGE = this.key("mistysurge")
    @JvmStatic val MOLD_BREAKER = this.key("moldbreaker")
    @JvmStatic val MOODY = this.key("moody")
    @JvmStatic val MOTOR_DRIVE = this.key("motordrive")
    @JvmStatic val MOXIE = this.key("moxie")
    @JvmStatic val MULTISCALE = this.key("multiscale")
    @JvmStatic val MULTITYPE = this.key("multitype")
    @JvmStatic val MUMMY = this.key("mummy")
    @JvmStatic val MYCELIUM_MIGHT = this.key("myceliummight")
    @JvmStatic val NATURAL_CURE = this.key("naturalcure")
    @JvmStatic val NEUROFORCE = this.key("neuroforce")
    @JvmStatic val NEUTRALIZING_GAS = this.key("neutralizinggas")
    @JvmStatic val NO_GUARD = this.key("noguard")
    @JvmStatic val NORMALIZE = this.key("normalize")
    @JvmStatic val OBLIVIOUS = this.key("oblivious")
    @JvmStatic val OPPORTUNIST = this.key("opportunist")
    @JvmStatic val ORICHALCUM_PULSE = this.key("orichalcumpulse")
    @JvmStatic val OVERCOAT = this.key("overcoat")
    @JvmStatic val OVERGROW = this.key("overgrow")
    @JvmStatic val OWN_TEMPO = this.key("owntempo")
    @JvmStatic val PARENTAL_BOND = this.key("parentalbond")
    @JvmStatic val PASTEL_VEIL = this.key("pastelveil")
    @JvmStatic val PERISH_BODY = this.key("perishbody")
    @JvmStatic val PICKPOCKET = this.key("pickpocket")
    @JvmStatic val PICKUP = this.key("pickup")
    @JvmStatic val PIXILATE = this.key("pixilate")
    @JvmStatic val PLUS = this.key("plus")
    @JvmStatic val POISON_HEAL = this.key("poisonheal")
    @JvmStatic val POISON_POINT = this.key("poisonpoint")
    @JvmStatic val POISON_PUPPETEER = this.key("poisonpuppeteer")
    @JvmStatic val POISON_TOUCH = this.key("poisontouch")
    @JvmStatic val POWER_CONSTRUCT = this.key("powerconstruct")
    @JvmStatic val POWER_OF_ALCHEMY = this.key("powerofalchemy")
    @JvmStatic val POWER_SPOT = this.key("powerspot")
    @JvmStatic val PRANKSTER = this.key("prankster")
    @JvmStatic val PRESSURE = this.key("pressure")
    @JvmStatic val PRIMORDIAL_SEA = this.key("primordialsea")
    @JvmStatic val PRISM_ARMOR = this.key("prismarmor")
    @JvmStatic val PROPELLER_TAIL = this.key("propellertail")
    @JvmStatic val PROTEAN = this.key("protean")
    @JvmStatic val PROTOSYNTHESIS = this.key("protosynthesis")
    @JvmStatic val PSYCHIC_SURGE = this.key("psychicsurge")
    @JvmStatic val PUNK_ROCK = this.key("punkrock")
    @JvmStatic val PURE_POWER = this.key("purepower")
    @JvmStatic val PURIFYING_SALT = this.key("purifyingsalt")
    @JvmStatic val QUARK_DRIVE = this.key("quarkdrive")
    @JvmStatic val QUEENLY_MAJESTY = this.key("queenlymajesty")
    @JvmStatic val QUICK_DRAW = this.key("quickdraw")
    @JvmStatic val QUICK_FEET = this.key("quickfeet")
    @JvmStatic val RAIN_DISH = this.key("raindish")
    @JvmStatic val RATTLED = this.key("rattled")
    @JvmStatic val RECEIVER = this.key("receiver")
    @JvmStatic val RECKLESS = this.key("reckless")
    @JvmStatic val REFRIGERATE = this.key("refrigerate")
    @JvmStatic val REGENERATOR = this.key("regenerator")
    @JvmStatic val RIPEN = this.key("ripen")
    @JvmStatic val RIVALRY = this.key("rivalry")
    @JvmStatic val RKS_SYSTEM = this.key("rkssystem")
    @JvmStatic val ROCK_HEAD = this.key("rockhead")
    @JvmStatic val ROCKY_PAYLOAD = this.key("rockypayload")
    @JvmStatic val ROUGH_SKIN = this.key("roughskin")
    @JvmStatic val RUN_AWAY = this.key("runaway")
    @JvmStatic val SAND_FORCE = this.key("sandforce")
    @JvmStatic val SAND_RUSH = this.key("sandrush")
    @JvmStatic val SAND_SPIT = this.key("sandspit")
    @JvmStatic val SAND_STREAM = this.key("sandstream")
    @JvmStatic val SAND_VEIL = this.key("sandveil")
    @JvmStatic val SAP_SIPPER = this.key("sapsipper")
    @JvmStatic val SCHOOLING = this.key("schooling")
    @JvmStatic val SCRAPPY = this.key("scrappy")
    @JvmStatic val SCREEN_CLEANER = this.key("screencleaner")
    @JvmStatic val SEED_SOWER = this.key("seedsower")
    @JvmStatic val SERENE_GRACE = this.key("serenegrace")
    @JvmStatic val SHADOW_SHIELD = this.key("shadowshield")
    @JvmStatic val SHADOW_TAG = this.key("shadowtag")
    @JvmStatic val SHARPNESS = this.key("sharpness")
    @JvmStatic val SHED_SKIN = this.key("shedskin")
    @JvmStatic val SHEER_FORCE = this.key("sheerforce")
    @JvmStatic val SHELL_ARMOR = this.key("shellarmor")
    @JvmStatic val SHIELD_DUST = this.key("shielddust")
    @JvmStatic val SHIELDS_DOWN = this.key("shieldsdown")
    @JvmStatic val SIMPLE = this.key("simple")
    @JvmStatic val SKILL_LINK = this.key("skilllink")
    @JvmStatic val SLOW_START = this.key("slowstart")
    @JvmStatic val SLUSH_RUSH = this.key("slushrush")
    @JvmStatic val SNIPER = this.key("sniper")
    @JvmStatic val SNOW_CLOAK = this.key("snowcloak")
    @JvmStatic val SNOW_WARNING = this.key("snowwarning")
    @JvmStatic val SOLAR_POWER = this.key("solarpower")
    @JvmStatic val SOLID_ROCK = this.key("solidrock")
    @JvmStatic val SOUL_HEART = this.key("soulheart")
    @JvmStatic val SOUNDPROOF = this.key("soundproof")
    @JvmStatic val SPEED_BOOST = this.key("speedboost")
    @JvmStatic val STAKEOUT = this.key("stakeout")
    @JvmStatic val STALL = this.key("stall")
    @JvmStatic val STALWART = this.key("stalwart")
    @JvmStatic val STAMINA = this.key("stamina")
    @JvmStatic val STANCE_CHANGE = this.key("stancechange")
    @JvmStatic val STATIC = this.key("static")
    @JvmStatic val STEADFAST = this.key("steadfast")
    @JvmStatic val STEAM_ENGINE = this.key("steamengine")
    @JvmStatic val STEELWORKER = this.key("steelworker")
    @JvmStatic val STEELY_SPIRIT = this.key("steelyspirit")
    @JvmStatic val STENCH = this.key("stench")
    @JvmStatic val STICKY_HOLD = this.key("stickyhold")
    @JvmStatic val STORM_DRAIN = this.key("stormdrain")
    @JvmStatic val STRONG_JAW = this.key("strongjaw")
    @JvmStatic val STURDY = this.key("sturdy")
    @JvmStatic val SUCTION_CUPS = this.key("suctioncups")
    @JvmStatic val SUPER_LUCK = this.key("superluck")
    @JvmStatic val SUPERSWEET_SYRUP = this.key("supersweetsyrup")
    @JvmStatic val SUPREME_OVERLORD = this.key("supremeoverlord")
    @JvmStatic val SURGE_SURFER = this.key("surgesurfer")
    @JvmStatic val SWARM = this.key("swarm")
    @JvmStatic val SWEET_VEIL = this.key("sweetveil")
    @JvmStatic val SWIFT_SWIM = this.key("swiftswim")
    @JvmStatic val SYMBIOSIS = this.key("symbiosis")
    @JvmStatic val SYNCHRONIZE = this.key("synchronize")
    @JvmStatic val SWORD_OF_RUIN = this.key("swordofruin")
    @JvmStatic val TABLETS_OF_RUIN = this.key("tabletsofruin")
    @JvmStatic val TANGLED_FEET = this.key("tangledfeet")
    @JvmStatic val TANGLING_HAIR = this.key("tanglinghair")
    @JvmStatic val TECHNICIAN = this.key("technician")
    @JvmStatic val TELEPATHY = this.key("telepathy")
    @JvmStatic val TERAFORMZERO = this.key("teraformzero")
    @JvmStatic val TERASHELL = this.key("terashell")
    @JvmStatic val TERASHIFT = this.key("terashift")
    @JvmStatic val TERAVOLT = this.key("teravolt")
    @JvmStatic val THERMAL_EXCHANGE = this.key("thermalexchange")
    @JvmStatic val THICK_FAT = this.key("thickfat")
    @JvmStatic val TINTED_LENS = this.key("tintedlens")
    @JvmStatic val TORRENT = this.key("torrent")
    @JvmStatic val TOUGH_CLAWS = this.key("toughclaws")
    @JvmStatic val TOXIC_BOOST = this.key("toxicboost")
    @JvmStatic val TOXIC_CHAIN = this.key("toxicchain")
    @JvmStatic val TOXIC_DEBRIS = this.key("toxicdebris")
    @JvmStatic val TRACE = this.key("trace")
    @JvmStatic val TRANSISTOR = this.key("transistor")
    @JvmStatic val TRIAGE = this.key("triage")
    @JvmStatic val TRUANT = this.key("truant")
    @JvmStatic val TURBOBLAZE = this.key("turboblaze")
    @JvmStatic val UNAWARE = this.key("unaware")
    @JvmStatic val UNBURDEN = this.key("unburden")
    @JvmStatic val UNNERVE = this.key("unnerve")
    @JvmStatic val UNSEEN_FIST = this.key("unseenfist")
    @JvmStatic val VESSEL_OF_RUIN = this.key("vesselofruin")
    @JvmStatic val VICTORY_STAR = this.key("victorystar")
    @JvmStatic val VITAL_SPIRIT = this.key("vitalspirit")
    @JvmStatic val VOLT_ABSORB = this.key("voltabsorb")
    @JvmStatic val WANDERING_SPIRIT = this.key("wanderingspirit")
    @JvmStatic val WATER_ABSORB = this.key("waterabsorb")
    @JvmStatic val WATER_BUBBLE = this.key("waterbubble")
    @JvmStatic val WATER_COMPACTION = this.key("watercompaction")
    @JvmStatic val WATER_VEIL = this.key("waterveil")
    @JvmStatic val WEAK_ARMOR = this.key("weakarmor")
    @JvmStatic val WELL_BAKED_BODY = this.key("wellbakedbody")
    @JvmStatic val WHITE_SMOKE = this.key("whitesmoke")
    @JvmStatic val WIMP_OUT = this.key("wimpout")
    @JvmStatic val WIND_POWER = this.key("windpower")
    @JvmStatic val WIND_RIDER = this.key("windrider")
    @JvmStatic val WONDER_GUARD = this.key("wonderguard")
    @JvmStatic val WONDER_SKIN = this.key("wonderskin")
    @JvmStatic val ZEN_MODE = this.key("zenmode")
    @JvmStatic val ZERO_TO_HERO = this.key("zerotohero")
    @JvmStatic val MOUNTAINEER = this.key("mountaineer")
    @JvmStatic val REBOUND = this.key("rebound")
    @JvmStatic val PERSISTENT = this.key("persistent")

    @ApiStatus.Internal
    fun register(consumer: (ResourceKey<AbilityTemplate>, AbilityTemplate) -> Unit) {
        var count = 0
        PotentialAbility.types.clear()
        PotentialAbility.types.add(CommonAbilityType)
        PotentialAbility.types.add(HiddenAbilityType)
        val baseKeys = this.keys()
        val abilityFlagsByShowdownId = AbilityFlag.entries.associateBy { it.showdownId }
        ShowdownService.service.getAbilities().forEach { jElement ->
            val jObject = jElement.asJsonObject
            val id = jObject.get("id").asString
            val rating = jObject.get("rating").asFloat
            val suppressWeather = jObject.get("suppressWeather").asBoolean
            val flags = jObject.getAsJsonObject("flags").entrySet().map { (key, value) ->
                if (value.asInt != 1) {
                    throw IllegalStateException("Received showdown flag $key with $value")
                }
                abilityFlagsByShowdownId[key]
                    ?: throw IllegalArgumentException("Unsupported AbilityFlag from showdown $key")
            }.toSet()
            val ability = this.create(id, rating, suppressWeather, flags)
            val resourceKey = ResourceKey.create(
                this.registryKey(),
                id.asIdentifierDefaultingNamespace()
            )
            if (!baseKeys.contains(resourceKey)) {
                throw IllegalArgumentException("No key $resourceKey for ability $id, please report to Cobblemon devs")
            }
            consumer(resourceKey, ability)
            count++
        }
        Cobblemon.LOGGER.info("Registered {} abilities", count)
    }

    fun get(name: String): AbilityTemplate? = this.registry().get(cobblemonResource(name))
    fun getOrException(name: String): AbilityTemplate = this.registry().getOrThrow(
        ResourceKey.create(
            this.registryKey(),
            cobblemonResource(name)
        )
    )

    override fun registry(): Registry<AbilityTemplate> = CobblemonRegistries.ABILITY

    override fun registryKey(): ResourceKey<Registry<AbilityTemplate>> = CobblemonRegistries.ABILITY_KEY

    private fun create(
        name: String,
        rating: Float,
        suppressWeather: Boolean,
        flags: Set<AbilityFlag>,
    ): AbilityTemplate {
        val id = cobblemonResource(name)
        val displayName = Component.translatable("${id.namespace}.ability.${id.path}")
        val description = Component.translatable("${id.namespace}.ability.${id.path}.desc")
        return AbilityTemplate(rating, suppressWeather, flags, displayName, description)
    }
}